### ISSUE TITLE
翻译质量问题

### ISSUE THREAD

**Issue by FrankHB** [ScottHuangZL/Rust-Articles-Translation#1]
https://github.com/ScottHuangZL/Rust-Articles-Translation/blob/master/Criticizing the Rust Language, and Why C_C++ Will Never Die.md
只看了一篇，觉得中文远不如英文通顺。本来打算开pr修正一下，但是数量……

transactional memory……交换型内存？
So if you happen to think that Rust is "good for any task", I have to disappoint you.
所以，我让你失望了如果你恰巧认为Rust是“适合所有任务”。
（……现在的机翻会这么热衷改分句语序吗。）
normal exceptions……普通表达式？
……

**Comment by ScottHuangZL** [comment]
Done to update.  The background is I use my weekend to rush out this translation, so I acknowledge it is not double check carefully, and just hope it is help to the people whose English is not good enough:)  

Welcome the reader to point out any issues, I will wry to correct it step by step, or open PR to correct directly:) thanks.

**Comment by kenpusney** [comment]
@FrankHB 🌍帝球居然也到这里来趟水了。

感觉满满的都是业余程序员翻译的痕迹。不过能做到这样也很不错了。

**Comment by ScottHuangZL** [comment]
Will continue to improve, thanks for your comments.
